UniWebApp/urls.py
from django.contrib import admin
from django.urls import path, include
from products.views import ProductListView
from customauth.views import sent
from customauth.views import login_page, register_page,logout_page
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('', ProductListView.as_view(), name='product-home'),
    path('login/', login_page, name='login'),
    path('logout/', logout_page, name='logout'),
    path('register/', register_page, name='register'),
    path('cart/', include("carts.urls", namespace='cart')),
    path('products/', include("products.urls", namespace='product')),
    path('orders/', include("orders.urls", namespace='orders')),
    path('send_mail/', sent, name='send_mail'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/urls.py
from django.urls import path, include
from carts.views import cart_home,cart_update,checkout_home,checkout_success

app_name = 'cart'

urlpatterns = [
    path('', cart_home, name='home'),
    path('checkout/', checkout_home,name='checkout'),
    path('update/',   cart_update,name='update'),
    path('success/',  checkout_success,name='success'),
]

user/urls.py
from django.contrib.auth import login
from django.urls import path
from . import views

urlpatterns = [
    path('',         views.user, name='user'),
    path('login/', login, {'template_name': 'user/login.html'})
]

carts/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import pre_save, post_save, m2m_changed
from products.models import Product


User = settings.AUTH_USER_MODEL


class CartManager(models.Manager):
    def new_or_get(self,request):
        cart_id = request.session.get("cart_id", None)
        qs = self.get_queryset().filter(id=cart_id)
        if qs.count() == 1:
            new_obj = False
            cart_obj = qs.first()
            if request.user.is_authenticated and cart_obj.user is None:
                cart_obj.user = request.user
                cart_obj.save()
        else:
            cart_obj = Cart.objects.new(user=request.user)
            new_obj = True
            request.session['cart_id'] = cart_obj.id
        return cart_obj,new_obj

    def new(self,user=None):
        user_obj = None
        print("in func", user)
        if user is not None:
            if user.is_authenticated:
                user_obj = user
        return self.model.objects.create(user=user_obj)


class Cart(models.Model):
    user = models.ForeignKey(User, null=True, blank=True, on_delete='CASCADE')
    products = models.ManyToManyField(Product, blank=True)
    subtotal = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    total = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    update = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    objects = CartManager()

    def __str__(self):
        return str(self.id)


def m2m_changed_cart_receiver(sender, instance, action, *args, **kwargs):
    if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
        products = instance.products.all()
        total_price = 0.0
        for product in products:
            total_price += float(product.price)
        if instance.subtotal != total_price:
            instance.subtotal = total_price
            instance.save()


m2m_changed.connect(m2m_changed_cart_receiver, sender=Cart.products.through)


def m2m_changed_cart_receiver_sale(sender,instance,*args,**kwargs):
    products = instance.products.all()
    price_with_sale = 0.0
    sale = 0.9
    for product in products:
        if product.sale:
            price_with_sale += float(product.price) * sale
        else:
            price_with_sale += float(product.price)
    instance.total = price_with_sale
    instance.save()


m2m_changed.connect(m2m_changed_cart_receiver_sale,sender=Cart.products.through)

carts/views.py
from django.shortcuts import render,redirect
from .models import Cart, Product
from orders.models import Order


def cart_home(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    return render(request,'carts/home.html', {"cart": cart_obj})


def cart_update(request):
    product_id = request.POST.get('product_id')
    product_obj = Product.objects.get(id=product_id)
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    if product_obj in cart_obj.products.all():
        cart_obj.products.remove(product_obj)
    else:
        cart_obj.products.add(product_obj)
    request.session['cart_items'] = cart_obj.products.count()
    return redirect('cart:home')


def checkout_home(request):
    if not request.user.is_authenticated:
        request.session['cart_items'] = 0
        del request.session['cart_id']
        return redirect("login")
    cart_obj, cart_created = Cart.objects.new_or_get(request)
    order_obj = None
    if cart_created or cart_obj.products.count() == 0:
        return redirect("cart:home")
    if request.user is not None:
        order_obj,order_obj_created = Order.objects.new_or_get(request.user,cart_obj)
        order_obj.save()
    if request.method == "POST":
        "check that order is done"
        is_done = order_obj.check_done()
        if is_done:
            order_obj.mark_paid()
            request.session['cart_items'] = 0
            del request.session['cart_id']
            return redirect("cart:success")

    context = {
            "object":order_obj,
            "billing_profile":request.user
        }
    return render(request, "carts/checkout.html", context)


def checkout_success(request):
    if not request.user.is_authenticated:
        return redirect("/")
    else:
        return render(request,"carts/success.html", {})

carts/templates/carts/checkout.html
{% extends "base.html" %}

{% block content %}
    <h1>Checkout</h1>
    <p>Cart total: {{ object.cart.total }}</p>
    <p>Shipping Total: {{ object.shipping_total }}</p>
    <p>Order Total: {{ object.total }}</p>

{% endblock %}

carts/templates/carts/home.html
{% extends 'base.html' %}

{% block content %}
<h1>Cart</h1>
    {% if cart.products.exists %}
        <table class="table" style="background-color: #fff;">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Product</th>
              <th scope="col">Price</th>
            </tr>
          </thead>
          <tbody>
          {% for product in cart.products.all %}
            <tr>
              <th scope="row">{{ forloop.counter }}</th>
                <td><a href="{{ product.get_absolute_url }}">{{ product.title }}</a>
                {% include 'products/snippets/update-cart.html' with product=product cart=cart in_cart=True %}
                </td>

              <td>{{ product.price }}</td>
            </tr>
          {% endfor %}
            <tr>
              <td colspan="1"></td>
              <td><b>Subtotal</b> {{ cart.subtotal }}</td>
              <td><b>Total</b> {{ cart.total }}</td>
            </tr>
          <tr>
              <td colspan="1"></td>
              <td><a class="btn  btn-success" href="{% url "cart:checkout" %}">Checkout</a> </td>
              <td></td>
            </tr>
          </tbody>
        </table>
    {% else %}
        <h3>Cart is empty</h3>
    {% endif %}
{% endblock %}

carts/templates/carts/success.html
{% extends 'base.html' %}

{% block content %}
    <div class="col-6 mx-auto py-2 text-center">
        <h class="display-4">THANKS FOR YOUR ORDER!!!</h>
        <div class="nav-link"><a href="{% url 'product-home' %}">Back to store</a></div>
    </div>

{% endblock %}