UniWebApp/urls.py
from django.contrib import admin
from django.urls import path, include
from products.views import ProductListView
from customauth.views import sent
from customauth.views import login_page, register_page,logout_page
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('', ProductListView.as_view(), name='product-home'),
    path('login/', login_page, name='login'),
    path('logout/', logout_page, name='logout'),
    path('register/', register_page, name='register'),
    path('cart/', include("carts.urls", namespace='cart')),
    path('products/', include("products.urls", namespace='product')),
    path('orders/', include("orders.urls", namespace='orders')),
    path('send_mail/', sent, name='send_mail'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/urls.py
from django.urls import path, include
from carts.views import cart_home,cart_update,checkout_home,checkout_success

app_name = 'cart'

urlpatterns = [
    path('', cart_home, name='home'),
    path('checkout/', checkout_home,name='checkout'),
    path('update/',   cart_update,name='update'),
    path('success/',  checkout_success,name='success'),
]

orders/urls.py
from django.urls import path, include
from orders.views import list_of_orders,detail

app_name = 'orders'

urlpatterns = [
    path('', list_of_orders, name='list'),
    path('<order_id>/', detail, name='detail')
]

products/urls.py
from django.urls import path, include
from products.views import ProductListView,ProductDetailView,create_product, edit_product, ProductDetailSlugView, ProductSaleListView,ProductSaleDetailView,make_sale_off, make_sale_on


app_name = 'product'

urlpatterns = [
    path('', ProductListView.as_view(), name='all'),
    path('create/', create_product, name='create'),
    path('sale_on/', make_sale_on, name='make-sale-on'),
    path('sale_off/', make_sale_off, name='make_sale_off'),
    path('sale/', ProductSaleListView.as_view(),name='sale'),
    path('sale/<int:pk>/', ProductSaleDetailView.as_view(), name='sale-detail'),
    path('<slug>/edit/', edit_product, name='edit'),
    path('<slug>/', ProductDetailSlugView.as_view(), name='detail'),
    # path('<int:pk>/edit/', edit_product),

]

user/urls.py
from django.contrib.auth import login
from django.urls import path
from . import views

urlpatterns = [
    path('',         views.user, name='user'),
    path('login/', login, {'template_name': 'user/login.html'})
]

templates/base.html
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">



    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-tagsinput.css' %}">

     {% load staticfiles %}
    <script src="{% static 'js/jquery-3.3.1.js' %}"></script>
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src={% static  'js/bootstrap-tagsinput.js'%}></script>


    <script src="{% static 'src/js/posts.js' %}"></script>
    <script src="{% static 'src/js/products.js' %}"></script>
    <script src="{% static 'src/js/send.js' %}"></script>

    {% if title %}
        <title>Shopping center - {{ title }}</title>
    {% else %}
        <title>Shop</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'product-home' %}">Shop-online</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'product-home' %}">Products</a>
                <a class="nav-item nav-link" href="{% url 'product:sale' %}">Sale products</a>
                {% if request.user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'orders:list' %}">My orders</a>
                <a class="nav-item nav-link" href="{% url 'cart:home' %}">{{ request.session.cart_items }} <i class="fa fa-shopping-cart" aria-hidden="true"></i></a>
                {% endif %}
            </div>
            <!-- Navbar Right Side -->
             {% if not request.user.is_authenticated %}
            <div class="navbar-nav">
              <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
              <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
            </div>
              {% endif %}
            {% if request.user.is_authenticated %}
                <div class="navbar-nav">
              <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
            </div>
            {% endif %}
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col">

          {% block content %}

          {% endblock %}
        </div>
        {% if request.user.is_superuser %}
          <div class="col-md-4">
            <div class="content-section">
            <h3>Admin Panel</h3>
            <p class='text-muted'>Choose the command for shop.
              <ul class="list-group">
                <li class="list-group-item list-group-item-light"><a href="{% url 'product:create' %}">Create</a></li>
                <li class="list-group-item list-group-item-light"><a href="{% url 'product:make-sale-on' %}">Make sale</a></li>
                <li class="list-group-item list-group-item-light"><a href="{% url 'product:make_sale_off' %}">Off sale for items</a></li>
              </ul>
            </p>
          </div>
        </div>
      {% endif %}
      </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


</body>
</html>

templates/login.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
{% if not user.is_authenticated %}
<form method="POST">

  <div class="container-login">
    {{ form }}
    <button type="submit">Login</button>
     </div>
</form>
{% endif %}
{% if user.is_authenticated %}
    <div class="container-login">
        <h1>You already authenticated</h1>
    </div>
    {% endif %}
{% endblock %}

templates/registration.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
    <form method="POST">
        <div class="container-login">
            {{ form }}
            <button type='submit' class='btn btn-default'>Register</button>
        </div>
    </form>


{% endblock %}

templates/send.html
{% extends 'base.html' %}
{% load staticfiles %}


{% block content %}
    <div class="post-title">
        <h1>Send Mail</h1>
    </div>
    <div class="spacer"></div>
    <form class="post-form">
        <div class="form-group">
            <label for="id_title_mail">Title:</label>
            <input class="form-control" id="id_title_mail" name="title_mail" type="text">
            <p id="id_warning_title" class="invisible warning-text">This should warn you!!!</p>
        </div>

        <div class="form-group">
            <label for="id_text_mail">Text:</label>
            <textarea id="id_text_mail" name="text_mail" rows="5" class="form-control"></textarea>
            <p id="id_warning_text" class="invisible warning-text">This should warn you!!!</p>
        </div>

        <div class="form-group">
            <label for="id_from_mail">Your email:</label>
            <input id="id_from_mail" name="mail_from" type="email" class="form-control" placeholder="name@example.com">
            <p id="id_warning_from" class="invisible warning-text">This should warn you!!!</p>
        </div>

            <div class="form-group">
                <label for="id_to_mail">Your email:</label>
                <input id="id_to_mail" name="mail_to" type="text" class="form-control" data-role="tagsinput">
                <p id="id_warning_to" class="invisible warning-text">This should warn you!!!</p>
            </div>

    </form>
    <button id="save_mail" class="save btn btn-default">Save</button>


{% endblock %}