UniWebApp/urls.py
from django.contrib import admin
from django.urls import path, include
from products.views import ProductListView
from customauth.views import sent
from customauth.views import login_page, register_page,logout_page
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('', ProductListView.as_view(), name='product-home'),
    path('login/', login_page, name='login'),
    path('logout/', logout_page, name='logout'),
    path('register/', register_page, name='register'),
    path('cart/', include("carts.urls", namespace='cart')),
    path('products/', include("products.urls", namespace='product')),
    path('orders/', include("orders.urls", namespace='orders')),
    path('send_mail/', sent, name='send_mail'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path, include
from products.views import ProductListView,ProductDetailView,create_product, edit_product, ProductDetailSlugView, ProductSaleListView,ProductSaleDetailView,make_sale_off, make_sale_on


app_name = 'product'

urlpatterns = [
    path('', ProductListView.as_view(), name='all'),
    path('create/', create_product, name='create'),
    path('sale_on/', make_sale_on, name='make-sale-on'),
    path('sale_off/', make_sale_off, name='make_sale_off'),
    path('sale/', ProductSaleListView.as_view(),name='sale'),
    path('sale/<int:pk>/', ProductSaleDetailView.as_view(), name='sale-detail'),
    path('<slug>/edit/', edit_product, name='edit'),
    path('<slug>/', ProductDetailSlugView.as_view(), name='detail'),
    # path('<int:pk>/edit/', edit_product),

]

user/urls.py
from django.contrib.auth import login
from django.urls import path
from . import views

urlpatterns = [
    path('',         views.user, name='user'),
    path('login/', login, {'template_name': 'user/login.html'})
]

products/models.py
from django.db import models
from django.urls import reverse
from django.db.models.signals import pre_save, post_save

from UniWebApp.utils import unique_slug_generator


# Create your models here.


class ProductManager(models.Manager):

    def sales(self):
        try:
            return Product.objects.filter(sale=True)
        except:
            return None

    def not_sales(self):
        try:
            return Product.objects.filter(sale=False)
        except:
            return None

    def get_by_slug(self, slug):
        try:
            return Product.objects.get(slug=slug)
        except:
            return None

    def get_by_id(self, id):
        qs = Product.objects.filter(id=id)  # Product.objects == self.get_queryset()
        if qs.count() == 1:
            return qs.first()
        return None


class Product(models.Model):
    title = models.CharField(max_length=120)
    slug = models.SlugField(blank=True,unique=True)
    description = models.TextField()
    price = models.DecimalField(decimal_places=2, max_digits=20, default=0.00)
    image = models.ImageField(upload_to='', null=True, blank=True)
    sale = models.BooleanField(default=False)

    objects = ProductManager()

    def get_absolute_url(self):
        # return "/products/{slug}/".format(slug=self.slug)
        return reverse("product:detail", kwargs={"slug":self.slug})

    def __str__(self):
        return self.title

    # def get_absolute_url(self):
    #     return reverse("make-sale-all", kwargs={"id": self.id})

    @staticmethod
    def get_all():
        products = Product.objects.all()
        return products


def product_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)


pre_save.connect(product_pre_save_receiver, sender=Product)

products/views.py
from django.http import Http404
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from .models import Product
from carts.models import Cart
from djongo.models import json
import json
from django.db import IntegrityError
from django.http import HttpResponse


# from products.forms import ProductForm

# Create your views here.
#

class ProductSaleListView(ListView):
    template_name = "products/sale-list.html"

    def get_queryset(self, *args, **kwargs):
        request = self.request
        return Product.objects.sales()


class ProductSaleDetailView(DetailView):

    def get_queryset(self, *args, **kwargs):
        return Product.objects.sales()


class ProductDetailSlugView(DetailView):
    queryset = Product.objects.all()
    template_name = "products/detail.html"

    def get_context_data(self, *args, **kwargs):
        context = super(ProductDetailSlugView, self).get_context_data(*args,**kwargs)
        cart_obj, new_obj = Cart.objects.new_or_get(self.request)
        context['cart'] = cart_obj
        return context

    def get_object(self, *args, **kwargs):
        request = self.request
        slug = self.kwargs.get('slug')
        try:
            instance = Product.objects.get(slug=slug)
        except Product.DoesNotExist:
            raise Http404("Not found..")
        except Product.MultipleObjectsReturned:
            qs = Product.objects.filter(slug=slug)
            instance = qs.first()
        except:
            raise Http404("Cannot get a object")
        return instance


# List of all Products
class ProductListView(ListView):
    template_name = "products/list.html"

    def get_queryset(self):
        request = self.request
        return Product.get_all()


def make_sale_off(request):
    try:
        Product.objects.sales().update(sale=False)
        return redirect('product:sale')
    except:
        return HttpResponse(status=301)


def make_sale_on(request):
    try:
        Product.objects.not_sales().update(sale=True)
        return redirect('product:sale')
    except:
        return HttpResponse(status=301)


# Detail of single Product
class ProductDetailView(DetailView):
    template_name = "products/detail.html"

    def get_context_data(self, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        return context

    def get_object(self, *args, **kwargs):
        request = self.request
        pk = self.kwargs.get('pk')
        instance = Product.objects.get_by_id(pk)
        if instance is None:
            raise Http404("Product doesn`t exist")
        return instance


def validate_data_product(posts):
    errors = {}
    if not posts['title']:
        errors['title'] = "This field is required!"
    else:
        if len(posts['title']) < 3:
            errors['title'] = "Len of title must be biggest then 3 characters"
        elif len(posts['title']) > 15:
            errors['title'] = "Len of title must be less then 10 characters"
    if not posts['description']:
        errors['title'] = "This field is required!"
    else:
        if len(posts['description']) > 280:
            errors['description'] = "Len of content must be less then 280 characters"
    try:
        if not posts['price']:
            errors['price'] = "This field is required!"
        else:
            size = float(posts['price'])
            if size <= 0.0:
                errors['price'] = "Price must be biggest then 0"
    except:
        errors['price'] = "Price must be integer!"
    return errors if errors else None


def create_product(request):
    if request.method == "POST":
        print("ff")
        data = json.loads(request.body)
        errors = validate_data_product(data)
        if not errors:
            post = Product(**data)
            try:
                post.save()
                return HttpResponse(status=201)
            except IntegrityError:
                errors = {'title': "Thing with this name already exists"}
                return HttpResponse(json.dumps(errors), status=400)
        else:
            return HttpResponse(json.dumps(errors), status=400)
    else:
        return render(request, 'products/create-product.html')


def edit_product(request, slug):
    post = Product.objects.get_by_slug(slug=slug)
    if request.method == "PUT":
        data = json.loads(request.body)
        errors = validate_data_product(data)
        if not errors:
            product = Product(**data)
            # rewrite all data
            post.title = product.title
            post.description = product.description
            post.price = product.price
            post.sale = product.sale
            post.save()
            return HttpResponse(status=201)
        else:
            return HttpResponse(json.dumps(errors), status=400)
    else:
        context = {
            'post': post
        }
        return render(request, 'products/edit-product.html', context)

products/templates/products/create-product.html
{% extends 'base.html' %}
{% load staticfiles %}


{% block content %}
    <div class="post-title">
        <h1>New Product</h1>
    </div>
    <div class="spacer"></div>
    <form class="post-form">
        <div class="form-group">
            <label for="id_title_product">Title:</label>
            <input class="form-control" id="id_title_product" name="title" type="text">
            <p id="id_warning_title" class="invisible   warning-text">This should warn you!!!</p>
        </div>

        <div class="form-group">
            <label for="id_description_product">Description:</label>
            <textarea id="id_description_product" name="description" rows="5" class="form-control"></textarea>
            <p id="id_warning_description" class="invisible warning-text">This should warn you!!!</p>
        </div>

        <div class="form-group">
            <label for="id_price_product">Price:</label>
            <input id="id_price_product" name="price" type="text" class="form-control">
            <p id="id_warning_price" class="invisible warning-text">This should warn you!!!</p>
        </div>

        <div class="form-group">
            <label class="form-check-label" for="id_sale_product">Sale:</label>
            <input id="id_sale_product" name="sale" type="checkbox" class=form-check-input">
            <p id="id_warning_sale" class="invisible warning-text">This should warn you!!!</p>
        </div>


{#        <div class="line">#}
{#            <h>Image</h>#}
{#            <label>#}
{#                <input id="id_image_product" name="image" type="file" accept="image/*">#}
{#                <p id="id_warning_sale" class="invisible warning-text">This should warn you!!!</p>#}
{#            </label>#}
{#        </div>#}

    </form>
    <button id="save_product" class="save btn btn-default">Save</button>


{% endblock %}

products/templates/products/detail.html
{% extends 'base.html' %}
{% block content %}
{% load staticfiles %}



    <div class="row">

    <div style="float: left;">
          <img src="{% static 'src/img/hmgoepprod.jpg' %}" height="250" width="160" />
      </div>
            <div class="col-12 col-md-10">
            <ul class="list-group list-group-flush">
              <li class="list-group-item"><h3>{{ object.title }}</h3></li>
              <li class="list-group-item">{{ object.description }}</li>
              <li class="list-group-item">{{ object.price }}</li>
              <li class="list-group-item">{% if object.sale %}Product have sale 10%{% endif %}</li>
            </ul>
        </div>
        <div class="col-12 col-md-2" style="padding: 0px">
            {% if request.user.is_authenticated %}
            {% if not request.user.is_superuser %}
            {% include 'products/snippets/update-cart.html' with product=object cart=cart %}
            {% endif %}
            {% endif %}
            {% if request.user.is_superuser %}
                <a href="{% url "product:edit" slug=object.slug  %}"  style="width: 81px;" class='btn btn-warning'>Edit</a>
            {% endif %}
        </div>
    </div>
{#<img src="{{ object.image.url }}" class="img-fluid" /><br>#}
{% endblock %}

products/templates/products/edit-product.html
{% extends 'base.html' %}
{% block content %}

    <div class="post-title">
        <h1>Edit {{ post.name }} {{ is_sale }}</h1>
    </div>
    <div class="spacer"></div>

    <form class="post-form">
        <div class="form-group">
            <label for="id_title_product">Title:</label>
            <input id="id_title_product" maxlength="30" name="name" type="text" value="{{ post.title }}" class="form-control">
            <p id="id_warning_title" class="invisible warning-text">This should warn you!!!</p>
        </div>

        <div class="form-group">
            <label for="id_description_product">Description:</label>
            <textarea  id="id_description_product" maxlength="620" name="description"
                             rows="5" class="form-control">{{ post.description }}</textarea>
            <p id="id_warning_description" class="invisible warning-text">This should warn you!!!</p>

        </div>

        <div class="form-group">

           <label for="id_price_product">Price:</label>
            <input id="id_price_product" maxlength="30" name="price" type="text" value="{{ post.price }}" class="form-control">
            <p id="id_warning_price" class="invisible warning-text">This should warn you!!!</p>
        </div>

        <div class="form-group">
            <input type="file" name="pic" accept="image/*">
        </div>

        <div class="form-group">
            <label class="form-check-label" for="id_sale_product">Sale:</label>
            {% if post.sale %}
            <input id="id_sale_product" name="sale" type="checkbox" class=form-check-input" value="{{ post.sale }}" checked>
            {% elif not post.sale %}
            <input id="id_sale_product" name="sale" type="checkbox" class=form-check-input" value="{{ post.sale }}">
            {% endif %}

             <p id="id_warning_sale" class="invisible warning-text">This should warn you!!!</p>
        </div>

    </form>
    <button id="update_room" class="save btn btn-default" onclick="update_product('{{ post.slug }}')">Save</button>

{% endblock %}

products/templates/products/list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
    {% for obj in object_list %}

        <div class="row-sm-12">
  <div class="col-sm-12">
    <div class="card" style="margin: 8px">
      <div class="card-body">
      <div style="float: left;margin-right: 10px">
          <img src="{% static 'src/img/hmgoepprod.jpg' %}" height="150" width="120" />
      </div>
      <div style="overflow: hidden;margin-bottom: 50px;">
          <h5 class="card-title">{{ obj.title }}</h5>
          <p class="card-text">{{ obj.price}}$</p>
      </div>
          <a href="{{ obj.get_absolute_url }}" class="btn btn-primary">Open product</a>
      </div>
    </div>
  </div>
</div>
    {% endfor %}
{% endblock content %}

products/templates/products/sale-list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
    {% for obj in object_list %}
{#        <article class="media content-section">#}
{#          <div class="media-body">#}
{#            <div class="article-metadata"></div>#}
{#            <h2><a class="article-title" href="{{ obj.get_absolute_url }}">{{ obj.title }}</a></h2>#}
{#            <p class="article-content">{{ obj.description}}</p>#}
{#          </div>#}
{#        </article>#}
        <div class="row-sm-12">
  <div class="col-sm-12">
    <div class="card" style="margin: 8px">
      <div class="card-body">
        <h5 class="card-title">{{ obj.title }}</h5>
        <p class="card-text">{{ obj.price}}$</p>
        <a href="{{ obj.get_absolute_url }}" class="btn btn-primary">Open product with sale</a>
      </div>
    </div>
  </div>
</div>
    {% endfor %}
{% endblock content %}